import 'jsr:@supabase/functions-js/edge-runtime.d.ts'

const TMDB='https://api.themoviedb.org/3'
const cors={
  'Access-Control-Allow-Origin':'*',
  'Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods':'POST, OPTIONS'
}

type Movie={id:number;title?:string;original_title?:string;overview?:string;release_date?:string;poster_path?:string|null;backdrop_path?:string|null;genre_ids?:number[];popularity?:number;vote_average?:number;vote_count?:number;adult?:boolean}
type Provider={provider_id:number;provider_name:string;logo_path?:string}
type Candidate={movie:Movie;sources:Set<string>;priority:number;score:number;why:string[];bucket:string;holiday:string|null;season:string|null}

const TRUSTED_COMPANY_QUERIES=['Hallmark Media','Crown Media Productions','MarVista Entertainment','Reel One Entertainment','Cartel Pictures','Johnson Production Group','Front Street Pictures','Muse Entertainment','Brain Power Studio','Incendo Productions','Larry Levinson Productions','Nicely Entertainment','Champlain Media','Synthetic Cinema International']
const TRUSTED_COMPANY_RX=[/hallmark|crown media/i,/marvista/i,/reel one/i,/cartel pictures/i,/johnson production group/i,/front street pictures/i,/muse entertainment/i,/brain power studio/i,/incendo/i,/larry levinson/i,/nicely entertainment/i,/champlain media/i,/synthetic cinema/i,/great american|gac family/i,/up faith|uptv/i]
const TITLE_SEARCHES=['autumn','fall','harvest','apple','pumpkin','halloween','thanksgiving','christmas','holiday','valentine','spring','summer','hometown','inn','bakery','ranch','vineyard','wedding','royal','mistletoe','snow','love']
const GENERIC_WHY=new Set(['romance','TV movie','Christmas','holiday','Halloween','Thanksgiving',"Valentine's",'Fall / harvest','Winter','Spring','Summer'])

function iso(d:Date){return d.toISOString().slice(0,10)}
function plusDays(d:Date,n:number){const x=new Date(d);x.setUTCDate(x.getUTCDate()+n);return x}
function norm(s:string){return s.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}

async function tmdb(path:string,token:string){const r=await fetch(TMDB+path,{headers:{Authorization:'Bearer '+token,accept:'application/json'}});if(!r.ok)throw new Error('TMDB '+r.status+': '+(await r.text()).slice(0,240));return await r.json()}
async function mapLimit<T,R>(items:T[],limit:number,fn:(v:T)=>Promise<R>){const out=new Array<R>(items.length);let next=0;await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(true){const i=next++;if(i>=items.length)break;out[i]=await fn(items[i])}}));return out}

function signals(m:Movie){
  const text=((m.title||'')+' '+(m.overview||'')).toLowerCase();const g=new Set(m.genre_ids||[]);let score=0;const why:string[]=[]
  const add=(label:string,pts:number,patterns:string[])=>{if(patterns.some(p=>text.includes(p))){score+=pts;why.push(label)}}
  if(g.has(10749)){score+=10;why.push('romance')} if(g.has(10770)){score+=12;why.push('TV movie')} if(g.has(35))score+=2;if(g.has(10751))score+=2
  add('Christmas',4,['christmas','mistletoe','santa','yuletide','christmas tree']);add('holiday',2,['holiday','festive']);add('Halloween',5,['halloween','haunted','spooky','trick or treat','costume party']);add('Thanksgiving',5,['thanksgiving','friendsgiving','turkey dinner']);add("Valentine's",4,['valentine','february 14']);add('Fall / harvest',7,['autumn','fall festival','harvest','october','pumpkin patch','apple orchard','apple picking','cider','hayride','corn maze']);add('Winter',3,['winter','snow','ski lodge','ski resort','blizzard']);add('Spring',3,['spring','springtime','garden festival','flower festival']);add('Summer',3,['summer','beach','seaside','lake house','summer camp','boardwalk','island vacation'])
  add('small town',10,['small town','small-town','quaint town','charming town']);add('hometown return',9,['hometown','returns home','return home','back home','comes home']);add('family business',8,['family business','family shop','family store','family bakery','family inn']);add('inn / lodge',8,[' inn ','lodge','bed and breakfast','b&b']);add('bakery',8,['bakery','baker','pastry shop']);add('ranch / farm',7,['ranch',' family farm','farmhouse']);add('vineyard / winery',7,['vineyard','winery','winemaker']);add('festival / town event',7,['festival','parade','town event','county fair','fairgrounds','regatta']);add('save-the-something plot',7,['save the ','saving the ','keep the ','struggling','keep her family','keep his family']);add('inheritance',7,['inherits','inheritance','inherited']);add('renovation',6,['renovat','restore the inn','restore her inn','restore his inn','fix up']);add('career-vs-love',6,['promotion','career opportunity','job offer','big city job','dream job','corporate']);add('old flame',7,['old flame','first love','childhood sweetheart','former sweetheart','reconnects with']);add('single parent',6,['single mom','single mother','single dad','single father']);add('dead spouse',6,['widow','widower','late husband','late wife']);add('fake relationship',7,['fake dating','pretend to date','pretend couple','fake relationship']);add('wedding',7,['wedding','bride','groom','engagement']);add('royalty',7,['prince','princess','royal','kingdom','duke','duchess']);add('competition',6,['competition','contest','regatta','bake-off','cook-off','pageant']);add('snowed-in',5,['snowed in','blizzard','snowstorm']);add('magic / wish',4,['magic','magical','wish comes true','christmas wish'])
  if(g.has(27))score-=20;if(g.has(80))score-=14;if(g.has(53))score-=12;if(g.has(10752))score-=20;if(g.has(28))score-=10;if(g.has(99))score-=20;if(!m.overview)score-=2
  return {score:Math.max(0,score),why:[...new Set(why)].slice(0,16)}
}

function holidayText(title:string,overview:string,keywords:string[]){const t=(title+' '+overview+' '+keywords.join(' ')).toLowerCase();if(/christmas|mistletoe|santa|yuletide/.test(t))return 'Christmas';if(/halloween|trick.?or.?treat|haunted|costume party|spooky season/.test(t))return 'Halloween';if(/thanksgiving|friendsgiving|turkey dinner/.test(t))return 'Thanksgiving';if(/valentine|february 14/.test(t))return "Valentine's Day";if(/new year/.test(t))return "New Year's";if(/easter/.test(t))return 'Easter';if(/st\. patrick|saint patrick/.test(t))return "St. Patrick's Day";if(/fourth of july|4th of july|independence day/.test(t))return 'Fourth of July';return null}
function seasonText(title:string,overview:string,keywords:string[],holiday:string|null){if(holiday==='Christmas'||holiday==="New Year's"||holiday==="Valentine's Day")return 'Winter';if(holiday==='Halloween'||holiday==='Thanksgiving')return 'Fall';if(holiday==='Easter'||holiday==="St. Patrick's Day")return 'Spring';if(holiday==='Fourth of July')return 'Summer';const t=(title+' '+overview+' '+keywords.join(' ')).toLowerCase();if(/autumn|\bfall\b|harvest|october|pumpkin|apple orchard|apple picking|cider|hayride|corn maze|leaf peep|changing leaves/.test(t))return 'Fall';if(/winter|snow|ski lodge|ski resort|blizzard|ice skating|frozen lake/.test(t))return 'Winter';if(/spring|springtime|garden festival|flower festival|blossom|tulip/.test(t))return 'Spring';if(/summer|beach|seaside|summer camp|island vacation|boardwalk|lake house|lakehouse|barbecue|bbq/.test(t))return 'Summer';return null}
function themeBucket(holiday:string|null,season:string|null){if(holiday==='Halloween')return 'Halloween';if(holiday==='Thanksgiving')return 'Thanksgiving';if(holiday==='Christmas')return 'Christmas';if(holiday==="Valentine's Day")return "Valentine's";if(holiday)return holiday;if(season==='Fall')return 'Fall / Harvest';if(season==='Winter')return 'Winter / Non-Christmas';if(season==='Spring')return 'Spring';if(season==='Summer')return 'Summer';return 'General Romance'}
function providerLabel(names:string[]){const order=[/hallmark/i,/lifetime/i,/great american|gac|pure flix/i,/up faith|uptv/i,/netflix/i,/prime video|amazon prime/i,/hulu/i,/peacock/i,/tubi/i,/roku/i];for(const rx of order){const hit=names.find(n=>rx.test(n));if(hit)return hit}return names[0]||'Streaming / TV'}
function trustedProductionHit(companies:string[]){const text=companies.join(' | ');return TRUSTED_COMPANY_RX.find(rx=>rx.test(text))?.source||null}

function cheeseLouiseProfile(args:{title:string;overview:string;genres:string[];productionCompanies:string[];why:string[];holiday:string|null;season:string|null;sources:string[]}){
  const genreText=args.genres.join(' ').toLowerCase();const combined=(args.title+' '+args.overview).toLowerCase();const hasRomance=/\bromance\b/.test(genreText)||/falls? (?:in )?love|falling in love|love interest|sweetheart|matchmaker|dating|engaged|fianc[eé]|wedding|romance/.test(combined);const isTvMovie=/tv movie/.test(genreText)||args.sources.some(s=>s.startsWith('company:'));const trustedHit=trustedProductionHit(args.productionCompanies);const hardGenre=/crime|thriller|war|documentary|action/.test(genreText);const tropeHits=[...new Set(args.why.filter(x=>!GENERIC_WHY.has(x)))];const seasonal=Boolean(args.holiday||args.season);const companySourced=args.sources.some(s=>s.startsWith('company:'))
  let eligible=false,fit='';if(trustedHit){eligible=true;fit='trusted Cheese Louise studio'}else if(companySourced&&hasRomance){eligible=true;fit='made-for-TV romance producer'}else if(hardGenre&&!hasRomance){eligible=false}else if(isTvMovie&&hasRomance&&tropeHits.length>=1){eligible=true;fit='TV romance + Romantiverse tropes'}else if(hasRomance&&seasonal&&tropeHits.length>=2){eligible=true;fit='seasonal Romantiverse romance'}else if(hasRomance&&tropeHits.length>=4){eligible=true;fit='strong Romantiverse trope profile'}
  const bonus=(trustedHit?35:0)+(companySourced?15:0)+(isTvMovie?8:0)+Math.min(20,tropeHits.length*3)+(seasonal?5:0);return {eligible,fit,bonus,tropeHits,trustedHit}
}

async function resolveTrustedCompanies(token:string){const rows=await mapLimit(TRUSTED_COMPANY_QUERIES,5,async query=>{try{const q=new URLSearchParams({query,language:'en-US',page:'1'});const data=await tmdb('/search/company?'+q.toString(),token);const target=norm(query);const hit=(data.results||[]).find((x:any)=>{const n=norm(x.name||'');return n===target||n.includes(target)||target.includes(n)})||(data.results||[])[0];return hit?.id?{id:Number(hit.id),name:String(hit.name||query),query}:null}catch(_){return null}});return rows.filter(Boolean) as {id:number;name:string;query:string}[]}
function addCandidate(map:Map<number,{movie:Movie;sources:Set<string>}>,movie:Movie,source:string){if(!movie?.id||movie.adult)return;const existing=map.get(movie.id);if(existing){existing.sources.add(source);return}map.set(movie.id,{movie,sources:new Set([source])})}
function rawCandidate(row:{movie:Movie;sources:Set<string>}):Candidate{const sig=signals(row.movie);const title=row.movie.title||row.movie.original_title||'';const overview=row.movie.overview||'';const holiday=holidayText(title,overview,[]);const season=seasonText(title,overview,[],holiday);const bucket=themeBucket(holiday,season);const sourceBonus=[...row.sources].reduce((sum,s)=>sum+(s.startsWith('company:')?45:s.startsWith('title:')?22:0),0);return {movie:row.movie,sources:row.sources,priority:sig.score+sourceBonus,score:sig.score,why:sig.why,bucket,holiday,season}}
function balancedTake<T extends {bucket:string}>(items:T[],limit:number,bucketOrder:string[]){const groups=new Map<string,T[]>();for(const item of items){const key=item.bucket||'General Romance';if(!groups.has(key))groups.set(key,[]);groups.get(key)!.push(item)}const order=[...bucketOrder,...[...groups.keys()].filter(k=>!bucketOrder.includes(k))];const out:T[]=[];let cursor=0;while(out.length<limit){let added=false;for(const key of order){const group=groups.get(key);if(group&&cursor<group.length){out.push(group[cursor]);added=true;if(out.length>=limit)break}}if(!added)break;cursor++}return out}

Deno.serve(async(req:Request)=>{
  if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return new Response(JSON.stringify({error:'POST required'}),{status:405,headers:{...cors,'Content-Type':'application/json'}})
  try{
    const token=Deno.env.get('TMDB_READ_ACCESS_TOKEN');if(!token)throw new Error('TMDB_READ_ACCESS_TOKEN is not configured');const input=await req.json().catch(()=>({}));const daysBack=Math.max(365,Math.min(5475,Number(input.days_back??5475)));const daysForward=Math.max(30,Math.min(730,Number(input.days_forward??730)));const maxResults=Math.max(24,Math.min(120,Number(input.max_results??120)));const today=new Date(),start=iso(plusDays(today,-daysBack)),end=iso(plusDays(today,daysForward));const candidates=new Map<number,{movie:Movie;sources:Set<string>}>()

    const companies=await resolveTrustedCompanies(token);const midpoint='2018-01-01';const companyJobs:string[]=[]
    for(const c of companies){for(const [from,to] of [[start,midpoint],[midpoint,end]]){for(let page=1;page<=3;page++){const q=new URLSearchParams({language:'en-US',region:'US',include_adult:'false',sort_by:'primary_release_date.desc','primary_release_date.gte':from,'primary_release_date.lte':to,with_companies:String(c.id),page:String(page)});companyJobs.push(`${c.id}|${c.name}|/discover/movie?${q.toString()}`)}}}
    const companyPages=await mapLimit(companyJobs,8,async job=>{const [id,name,...pathParts]=job.split('|');const path=pathParts.join('|');try{return {id,name,data:await tmdb(path,token)}}catch(_){return {id,name,data:{results:[]}}}});for(const page of companyPages)for(const m of(page.data?.results||[]))addCandidate(candidates,m,`company:${page.name}`)

    const titleJobs:string[]=[];for(const term of TITLE_SEARCHES){for(let page=1;page<=2;page++){const q=new URLSearchParams({query:term,language:'en-US',include_adult:'false',region:'US',page:String(page)});titleJobs.push(`${term}|/search/movie?${q.toString()}`)}}
    const titlePages=await mapLimit(titleJobs,8,async job=>{const [term,...parts]=job.split('|');const path=parts.join('|');try{return {term,data:await tmdb(path,token)}}catch(_){return {term,data:{results:[]}}}});for(const page of titlePages){for(const m of(page.data?.results||[])){const d=m.release_date||'';if(d&&(d<start||d>end))continue;addCandidate(candidates,m,`title:${page.term}`)}}

    const currentYear=today.getUTCFullYear();const genericJobs:string[]=[];for(let year=Math.max(new Date(start+'T00:00:00Z').getUTCFullYear(),currentYear-7);year<=new Date(end+'T00:00:00Z').getUTCFullYear();year++){const from=`${year}-01-01`,to=`${year}-12-31`;for(const genre of ['10749','10770'])for(let page=1;page<=2;page++){const q=new URLSearchParams({language:'en-US',region:'US',include_adult:'false',sort_by:'primary_release_date.desc','primary_release_date.gte':from,'primary_release_date.lte':to,with_genres:genre,page:String(page)});genericJobs.push(`/discover/movie?${q.toString()}`)}}
    const genericPages=await mapLimit(genericJobs,8,path=>tmdb(path,token).catch(()=>({results:[]})));for(const page of genericPages)for(const m of(page.results||[]))addCandidate(candidates,m,'generic')

    const bucketOrder=['Fall / Harvest','Halloween','Thanksgiving','General Romance','Christmas','Winter / Non-Christmas','Spring','Summer',"Valentine's"];const raw=[...candidates.values()].map(rawCandidate).sort((a,b)=>b.priority-a.priority||(b.movie.release_date||'').localeCompare(a.movie.release_date||''));const preselected=balancedTake(raw,Math.min(190,raw.length),bucketOrder)

    const enriched=await mapLimit(preselected,7,async entry=>{let detail:any={},providerData:any={};try{const q=new URLSearchParams({language:'en-US',append_to_response:'keywords,credits,external_ids'});const [d,p]=await Promise.all([tmdb('/movie/'+entry.movie.id+'?'+q.toString(),token),tmdb('/movie/'+entry.movie.id+'/watch/providers',token)]);detail=d||{};providerData=p||{}}catch(_){try{providerData=await tmdb('/movie/'+entry.movie.id+'/watch/providers',token)}catch(__){}}
      const us=providerData?.results?.US||{};const all=[...(us.flatrate||[]),...(us.free||[]),...(us.ads||[]),...(us.buy||[]),...(us.rent||[])] as Provider[];const seen=new Set<number>();const providers=all.filter(p=>p?.provider_id&&!seen.has(p.provider_id)&&seen.add(p.provider_id));const providerNames=providers.map(p=>p.provider_name).filter(Boolean);const keywords=(detail?.keywords?.keywords||[]).map((k:any)=>k?.name).filter(Boolean).slice(0,30);const genres=(detail?.genres||[]).map((g:any)=>g?.name).filter(Boolean);const productionCompanies=(detail?.production_companies||[]).map((c:any)=>c?.name).filter(Boolean).slice(0,16);const title=detail?.title||entry.movie.title||entry.movie.original_title||'Untitled';const overview=detail?.overview||entry.movie.overview||'';const holiday=holidayText(title,overview,keywords);const season=seasonText(title,overview,keywords,holiday);const sig=signals({...entry.movie,title,overview,genre_ids:entry.movie.genre_ids});const sources=[...entry.sources];const profile=cheeseLouiseProfile({title,overview,genres,productionCompanies,why:sig.why,holiday,season,sources})
      return {eligible:profile.eligible,fit:profile.fit,tmdb_id:entry.movie.id,tmdb_type:'movie',title,summary:overview,tagline:detail?.tagline||null,keywords,genres,production_companies:productionCompanies,cast_characters:(detail?.credits?.cast||[]).map((c:any)=>c?.character).filter(Boolean).slice(0,16),external_ids:detail?.external_ids||{},premiere_date:detail?.release_date||entry.movie.release_date||null,poster_url:(detail?.poster_path||entry.movie.poster_path)?'https://image.tmdb.org/t/p/w500'+(detail?.poster_path||entry.movie.poster_path):null,backdrop_url:(detail?.backdrop_path||entry.movie.backdrop_path)?'https://image.tmdb.org/t/p/w780'+(detail?.backdrop_path||entry.movie.backdrop_path):null,source_url:'https://www.themoviedb.org/movie/'+entry.movie.id,watch_url:us.link||null,providers:providerNames,network:providerLabel(providerNames),holiday,season,bucket:themeBucket(holiday,season),match_score:Math.min(100,sig.score+profile.bonus),why:[...new Set([...(profile.trustedHit?[`trusted studio: ${profile.trustedHit}`]:[]),...(profile.fit?[profile.fit]:[]),...sig.why])].slice(0,14),discovery_sources:sources,popularity:Number(detail?.popularity??entry.movie.popularity??0),vote_average:Number(detail?.vote_average??entry.movie.vote_average??0),vote_count:Number(detail?.vote_count??entry.movie.vote_count??0)}
    })

    const qualified=enriched.filter((x:any)=>x.eligible).sort((a:any,b:any)=>b.match_score-a.match_score||(b.premiere_date||'').localeCompare(a.premiere_date||'')||b.popularity-a.popularity);const backbone=qualified.filter((x:any)=>x.discovery_sources.some((s:string)=>s.startsWith('company:'))).slice(0,36);const backboneIds=new Set(backbone.map((x:any)=>x.tmdb_id));const remainder=qualified.filter((x:any)=>!backboneIds.has(x.tmdb_id));const mixed=balancedTake(remainder,Math.max(0,maxResults-backbone.length),bucketOrder);const results=[...backbone,...mixed].slice(0,maxResults);const coverage=results.reduce((acc:any,item:any)=>{const k=item.bucket||'General Romance';acc[k]=(acc[k]||0)+1;return acc},{});const benchmark=results.find((x:any)=>norm(x.title)==='autumn at apple hill')||qualified.find((x:any)=>norm(x.title)==='autumn at apple hill')||null

    return new Response(JSON.stringify({generated_at:new Date().toISOString(),window:{start,end},trusted_companies:companies.map(c=>c.name),scanned_candidates:candidates.size,enriched_candidates:enriched.length,qualified_candidates:qualified.length,rejected_candidates:enriched.length-qualified.length,count:results.length,coverage,benchmark:{autumn_at_apple_hill_found:Boolean(benchmark),rank:benchmark?results.findIndex((x:any)=>x.tmdb_id===benchmark.tmdb_id)+1:null},results,attribution:{movie_data:'TMDB',streaming_availability:'JustWatch via TMDB',discovery:['trusted production companies','Romantiverse title vocabulary','romance/TV-movie fallback']}}),{headers:{...cors,'Content-Type':'application/json','Cache-Control':'private, max-age=300'}})
  }catch(e){const message=e instanceof Error?e.message:String(e);console.error(message);return new Response(JSON.stringify({error:message}),{status:500,headers:{...cors,'Content-Type':'application/json'}})}
})
